name: Send Contest Reminder Emails

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes UTC
  workflow_dispatch:

jobs:
  run-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install

      - name: 📦 Install ts-node and typescript
        run: npm install ts-node typescript --save-dev

      - name: 🚀 Run the cron job
        run: npm run cron
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          RESEND_FROM: ${{ secrets.RESEND_FROM }}
